# Site settings
title: Sea \'n Cliffs
email: rorystephenson@gmail.com
description: >
  This will be the description...
domain: seancliffs.github.io
url: https://seancliffs.github.io
baseurl: /seancliffs

twitter_username:
github_username:

# Build settings
markdown: kramdown
