# Site settings
title: Sea \'n Cliffs
email: rorystephenson@gmail.com
description: >
  This will be the description...
domain: seandcliffs.com
url: https://seandcliffs.com

# Build settings
markdown: kramdown

collections:
  escursioni:
    output: true
  gallery:
    output: true
  blog:
    output: true
