backend:
  name: github
  repo: seancliffs/seancliffs
  branch: master
  site_domain: epic-goldberg-f806a5.netlify.app
media_folder: 'img/uploads'
collections:
  - name: '_pages_'
    label: 'Pages'
    files:
      - label: 'Section names'
        name: 'section_names'
        file: '_data/sections.yaml'
        fields:
          - { label: "Esplora", name: "esplora", widget: "string" }
          - { label: "Escursioni", name: "escursioni", widget: "string" }
          - { label: "Foto & Video", name: "foto_video", widget: "string" }
          - { label: "About", name: "about", widget: "string" }
          - { label: "Contatti", name: "contatti", widget: "string" }
      - label: 'Home page'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "front" }
          - { label: "Header title", name: "header_title", widget: "string" }
          - { label: "Header subtitle", name: "header_subtitle", widget: "string" }
          - { label: "Header image", name: "header_image", widget: "image" }
          - { label: "Esplora book now text", name: "esplora_book_now_text", widget: "string" }
          - { label: "Esplora titolo", name: "esplora_title", widget: "string" }
          - { label: "Esplora descrizione", name: "esplora_description", widget: "string" }
          - { label: "Esplora image", name: "esplora_image", widget: "string" }
          - { label: "About content", name: "about_content", widget: "markdown" }
          - { label: "Contatti content", name: "contatti_content", widget: "markdown" }
  - name: 'gallery'
    label: 'Gallery'
    folder: '_gallery/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Image link", name: "image", widget: "image" }
      - { label: "Youtube link", name: "body", widget: "string" }
  - name: 'escursioni'
    label: 'Escursioni'
    folder: '_escursioni/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
