backend:
  name: github
  repo: seancliffs/seancliffs
  branch: master
  site_domain: epic-goldberg-f806a5.netlify.app
media_folder: 'img/uploads'
collections:
  - name: '_pages_'
    label: 'Pages'
    files:
      - label: 'Section names'
        name: 'section_names'
        file: '_data/sections.yaml'
        fields:
          - { label: "Esplora", name: "esplora", widget: "string", i18n: true }
          - { label: "Escursioni", name: "escursioni", widget: "string", i18n: true }
          - { label: "Foto & Video", name: "foto_video", widget: "string", i18n: true }
          - { label: "Blog", name: "blog", widget: "string", i18n: true }
          - { label: "Contatti", name: "contatti", widget: "string", i18n: true }
          - { label: "Mappa Escursioni", name: "mappa_escursioni", widget: "string", i18n: true }
          - { label: "Chi Siamo", name: "chi_siamo", widget: "string", i18n: true }
      - label: 'Home page'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "front", i18n: false }
          - { label: "Header image", name: "header_image", widget: "image", i18n: false }
          - { label: "Header title", name: "header_title", widget: "string", i18n: true }
          - { label: "Header subtitle", name: "header_subtitle", widget: "markdown", i18n: true }
          - { label: "Scopri di piu button", name: "scopri_di_piu", widget: "string", i18n: true }
          - { label: "Introduction", name: "introduction", widget: "markdown", i18n: true }
          - { label: "Esplora book now text", name: "esplora_book_now_text", widget: "string", i18n: true }
          - { label: "Esplora titolo", name: "esplora_title", widget: "string", i18n: true }
          - { label: "Esplora descrizione", name: "esplora_description", widget: "markdown", i18n: true }
          - { label: "Esplora image", name: "esplora_image", widget: "string", i18n: false }
          - { label: "About content", name: "about_content", widget: "markdown", i18n: true }
          - { label: "Contatti content", name: "contatti_content", widget: "markdown", i18n: true }

      - label: 'Mappa Escursioni'
        name: 'mappa_escursioni'
        file: '_data/mappa-escursioni.yaml'
        fields:
          - { label: "Variant", name: "variant", widget: "hidden", default: "escursione", i18n: false }
          - { label: "Header image", name: "image", widget: "image", i18n: false }
          - { label: "Header title", name: "title", widget: "string", i18n: true }
          - { label: "Content", name: "content", widget: "markdown", i18n: true }
      - label: 'Chi Siamo'
        name: 'chi_siamo'
        file: '_data/chi-siamo.yaml'
        fields:
          - { label: "Header image", name: "image", widget: "image", i18n: false }
          - { label: "Header title", name: "title", widget: "string", i18n: true }
          - { label: "Content", name: "content", widget: "markdown", i18n: true }
  - name: 'gallery'
    label: 'Gallery'
    folder: '_gallery/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n:
      structure: multiple_files
      locales: [it, en]
      default_locale: it
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false, i18n: false }
      - { label: "Image link", name: "image", widget: "image", required: false, i18n: false }
      - { label: "Youtube link", name: "youtube_link", widget: "string", required: false, i18n: false }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Caption", name: "caption", widget: "string", i18n: true }
  - name: 'escursioni'
    label: 'Escursioni'
    folder: '_escursioni/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n:
      structure: multiple_files
      locales: [it, en]
      default_locale: it
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page", i18n: false }
      - { label: "Image", name: "image", widget: "image", i18n: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", i18n: false }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: 'blog'
    label: 'Blog'
    folder: '_blog/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n:
      structure: multiple_files
      locales: [it, en]
      default_locale: it
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page", i18n: false }
      - { label: "Image", name: "image", widget: "image", i18n: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", i18n: false }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
