backend:
  name: github
  repo: seancliffs/seancliffs
  branch: master
  site_domain: epic-goldberg-f806a5.netlify.app

media_folder: 'img/uploads'

i18n:
  structure: single_file
  locales: [it, en]
  default_locale: it

collections:
  - name: '_pages_'
    label: 'Pages'
    i18n:
      structure: single_file
      locales: [it, en]
      default_locale: it
    files:
      - label: 'Section names'
        name: 'section_names'
        file: '_data/sections.yaml'
        i18n: true
        fields:
          - { label: "Esplora", name: "esplora", widget: "string", i18n: true }
          - { label: "Escursioni", name: "escursioni", widget: "string", i18n: true }
          - { label: "Foto & Video", name: "foto_video", widget: "string", i18n: true }
          - { label: "Contatti", name: "contatti", widget: "string", i18n: true }
          - { label: "Mappa Escursioni", name: "mappa_escursioni", widget: "string", i18n: true }
          - { label: "Chi Siamo", name: "chi_siamo", widget: "string", i18n: true }
      - label: 'Home page'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "front" }
          - { label: "Header title", name: "header_title", widget: "string" }
          - { label: "Header subtitle", name: "header_subtitle", widget: "markdown" }
          - { label: "Header image", name: "header_image", widget: "image" }
          - { label: "Introduction", name: "introduction", widget: "markdown" }
          - { label: "Esplora book now text", name: "esplora_book_now_text", widget: "string" }
          - { label: "Esplora titolo", name: "esplora_title", widget: "string" }
          - { label: "Esplora descrizione", name: "esplora_description", widget: "markdown" }
          - { label: "Esplora image", name: "esplora_image", widget: "string" }
          - { label: "About content", name: "about_content", widget: "markdown" }
          - { label: "Contatti content", name: "contatti_content", widget: "markdown" }

      - label: 'Mappa Escusioni'
        name: 'mappa_escursioni'
        file: 'pages/mappa-escursioni.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page" }
          - { label: "Variant", name: "variant", widget: "hidden", default: "escursione" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/mappa-escursioni" }
          - { label: "Header title", name: "title", widget: "string" }
          - { label: "Header image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Chi Siamo'
        name: 'chi_siamo'
        file: 'pages/chi-siamo.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/chi-siamo" }
          - { label: "Header title", name: "title", widget: "string" }
          - { label: "Header image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: 'gallery'
    label: 'Gallery'
    folder: '_gallery/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Image link", name: "image", widget: "image", required: false }
      - { label: "Youtube link", name: "youtube_link", widget: "string", required: false }
  - name: 'escursioni'
    label: 'Escursioni'
    folder: '_escursioni/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'blog'
    label: 'Blog'
    folder: '_blog/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "plain-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
